version: '3'

services:

  todoback:
    image: todobackend:latest
    ports:
      - 3001:3001

  todofront:
    image: todofrontend:latest
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todobackend
    depends_on:
      - "todoback"

  todotests:
    image: todotests:latest
    environment:
      - FRONT_HOST=todofrontend
    depends_on:
      - "todoback"
      - "todofront"
